source "https://rubygems.org"

gem 'rake', '~> 10.0'
gem 'jekyll', '~> 2.0'
gem 'octopress-hooks', '~> 2.2'
gem 'octopress-date-format', '~> 2.0'
gem 'jekyll-sitemap'
gem 'rdiscount', '~> 2.0'
gem 'RedCloth', '~> 4.2.9'
gem 'haml', '~> 4.0'
gem 'compass'
gem 'sass-globbing'
gem 'rubypants', '~> 0.2.0'
gem 'rb-fsevent', '~> 0.9'
gem 'stringex', '~> 1.4.0'
gem 'octopress'
gem 'neat'
gem 'bourbon'
gem 'bitters'
gem 'aws-sdk'
gem 'jekyll-assets'
gem 'uglifier'
gem 'sinatra', '~> 1.4.2'
